/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RareRouteImport } from './routes/rare'
import { Route as IndexRouteImport } from './routes/index'

const RareRoute = RareRouteImport.update({
  id: '/rare',
  path: '/rare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rare': typeof RareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rare': typeof RareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rare': typeof RareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rare'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rare'
  id: '__root__' | '/' | '/rare'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RareRoute: typeof RareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rare': {
      id: '/rare'
      path: '/rare'
      fullPath: '/rare'
      preLoaderRoute: typeof RareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RareRoute: RareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
